### ISSUE TITLE
[Fix] Remove as much custom CSS styles from input as possible

### ISSUE THREAD

**Issue by BrainCrumbz** [kekeh/mydatepicker#151]
The rationale is that the input field should very likely keep the same style as the rest of page. So e.g. keep rounded corners, or smaller text, or lighter text weight, or differnt text color. Ideally, the CSS styling imposed by the library could be as minimal as possible just to give a proper look when datepicker is opened/closed, and to style buttons within the input (open, clear). But for example font-related styles could be inherited, and where style is needed, use CSS classes, not inline rules.

From a CSS styles rundown on input element, here are some of them flagged with `/****/` for *potential* removal: 

```css
/* inline styles */
element.style {
    height: 34px;
    line-height: 34px;  /****/
    font-size: 14px;  /****/
    border: none;  /****/
    padding-right: 30px;  /****/
}

.mydp .btnclear, .mydp .btnpicker, .mydp .headerbtn, .mydp .headermonthtxt, .mydp .headertodaybtn, .mydp .headeryeartxt, .mydp .selection {
    color: #000;  /****/
}

.mydp .selection {
    outline: 0;
    background-color: #FFF;  /****/
    display: table-cell;
    position: absolute;
    width: 100%;
    font-weight: 700;  /****/
    text-overflow: ellipsis;
    text-align: center;  /****/
}

.mydp * {
    -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    font-family: Arial,Helvetica,sans-serif;  /****/
    padding: 0;  /****/
    margin: 0;  /****/
}
```

This was just a quick rundown, there might be others on other component parts.

What do you think about it? Thanks for your time

PS I dubbed this item as "[Fix]" as the general user page style looks quite broken as is, see e.g. this example (ignore alignment please):

![mydatepicker-sample](https://cloud.githubusercontent.com/assets/3185573/21999107/b0ae7e02-dc38-11e6-9dfd-ba47202a6e55.png)

**Comment by kekeh** [comment]
You can try this: https://github.com/kekeh/ngx-mydatepicker

It is attribute directive datepicker and you can set your own styles to input box, calendar and clear buttons.

Here is demo which input box and buttons are bootstrap styled: https://kekeh.github.io/ngx-mydatepicker/

This component is not yet well tested but you can try.

**Comment by BrainCrumbz** [comment]
[Late reply] Are you planning to drop this library in favour of the other ngx- one? Otherwise, would you consider a PR on this library at least to turn inline styles into classes?

**Comment by kekeh** [comment]
No plan to remove inline styles, because it breaks whole date picker. You can control them by options and classes don't work in this case.

If you want full control to input box, calendar and close buttons you can use this date picker:

repo: https://github.com/kekeh/ngx-mydatepicker
demo (bootstrap style): https://kekeh.github.io/ngx-mydatepicker

**Comment by BrainCrumbz** [comment]
Okay, Just wondering, are you sure all current inline styles are needed like that? At the moment we are overriding some of them (e.g. fixed height on input and button wrapper) with simple classes, *from the outside* of the component, so those can definitely be moved out to CSS classes. 

Now we're forced to use `!important` though, to override inline styles, which is a pity. We'd be happy to submit a PR which just some styles moved from inline to classes, but after all, it's up to you.

BTW not switching for not to the other library, as you mentioned is not heavily tested yet. Maybe later, after more adoption and feedbacks? Thanks though!

**Comment by kekeh** [comment]
I set inline styles by **[ngStyle]** directive because I don't know any other way (class is not working in this case because they are configurable). Now there is the following inline styles:
- height (you can set component height in options)
- line-height (position text horizontally)
- font-size (you can set input font size in options)
- padding-right (position text vertically)

ngx-mydatepicker is quite well tested now. If you are already using bootstrap there are ready made examples in the README file.

**Comment by BrainCrumbz** [comment]
Thanks for the info! Not sure when you say class is not working because they are configurable.

From my team general understanding, it's much better when one keeps style-related topics out of code, and into the CSS realm. So, for example, if one has a library and wants to give library users the option to change height, or line-height, etc. with respect to default, I guess one should not be forced to pass those values to some option/configuration object. CSS is already made for that, and one cannot expose *all* possible styles through the object. One should know that there are some well-known CSS classes with their style, they become part of the component public API (just not code API, but for style), and if library user want to change style, s/he can just override with own CSS classes.

On the other hand, one could keep configuration object for things beyond pure styling, e.g. functional aspects, behaviour, enabling/disabling. Possibly even issues a little bit on the frontier, like showing/hiding part of the component UI ... not sure about those: if component style is able to self-adapt its layout to missing parts, maybe one could still prefer going with the CSS route.

How do you see that?

**Comment by kekeh** [comment]
I changed style of input box. Now it is like bootstrap style. With default options it is:

![screenshot_2017-04-12_10-17-46](https://cloud.githubusercontent.com/assets/11028839/24945862/9bc7ac7e-1f69-11e7-8a91-b165e6737ed0.png)

New version is: 1.9.0

Here is online demo: http://kekeh.github.io/mydatepicker

If you want bootstrap style probably you can remove important style definitions.

**Comment by BrainCrumbz** [comment]
Probably something specific will remain, like the background color on button hover. Others like height should go. Thanks for the update!

**Comment by kekeh** [comment]
What kind of background color on button hover should be?

**Comment by BrainCrumbz** [comment]
As of today, Bootstrap style shows a gray background on hover instead of blue one:

![css bootstrap - google chrome](https://cloud.githubusercontent.com/assets/3185573/24960724/e72adcae-1f96-11e7-88cc-850fc91f8cc1.png)

http://getbootstrap.com/css/#buttons

**Comment by BrainCrumbz** [comment]
If that may help you somehow, here's the set of style we're overriding (against mydatepicker 1.8.5):

```css
/* reset MyDatePicker custom font styles to Bootstrap styles */

.my-web-app .mydp {
  border-radius: 4px;
}

.my-web-app .has-success .mydp {
  border-color: #3C763D;
}

.my-web-app .mydp .selectiongroup {
  border: 1px solid transparent;
  border-radius: 4px;
}

.my-web-app .mydp .selection {
  height: 30px!important;
  font-weight: inherit;
  font-family: inherit;
  text-align: inherit;
  padding: 6px 12px;
}

.my-web-app fieldset[disabled] .mydp .selection {
  background-color: #EEE;
  opacity: 1;
  cursor: not-allowed;
}

.my-web-app .mydp .selbtngroup {
  height: 30px!important;
}

.my-web-app .mydp .btnclear:hover,
.my-web-app .mydp .btnpicker:hover  {
  background-color: #E6E6E6;
  border-color: #ADADAD;
}

.my-web-app fieldset[disabled] .mydp .btnclear,
.my-web-app fieldset[disabled] .mydp .btnpicker {
  cursor: not-allowed;
}

.my-web-app fieldset[disabled] .mydp .btnclear:hover,
.my-web-app fieldset[disabled] .mydp .btnpicker:hover {
  background-color: #FFF;
}

.my-web-app .mydp .icon-cross:before {
  font-family: 'Glyphicons Halflings';
  font-size: 14px;
  content: '\e014';
}
```
