### ISSUE TITLE
Why can't I display correct icons?

### ISSUE THREAD

**Issue by Liranius** [kekeh/mydatepicker#334]
Sorry to bother you. When I imported your module to my app, all icons were displaying incorrectly. Please see the snapshot below. 
![image](https://user-images.githubusercontent.com/16535593/26875122-0482e0ba-4bb3-11e7-87b4-c88cf7297f62.png)

However, your online demo display icons properly. So I'm wondering if there are more configurations than listed in the readme.

**Comment by kekeh** [comment]
Try to add the following definition to your css file.
```css
.mydp .mydpicon:before { 
    font-family: mydatepicker !important; 
}
```
