### ISSUE TITLE
Change disabled day background color

### ISSUE THREAD

**Issue by picosam** [kekeh/mydatepicker#374]
Hello, try as I may, even through `!important` CSS values, I'm unable to change the disabled day's background color... any idea why? Thanks!

**Comment by kekeh** [comment]
It is already important.

```css
.mydp .disabled {
    cursor: default !important;
    color: #CCC !important;
    background: #FBEFEF !important;
}
```
If you want to change style. Easiest way is to create own version of the component. You can start from here: https://github.com/kekeh/mydatepicker#development-of-this-component
