### ISSUE TITLE
Icons not displaying on datepicker

### ISSUE THREAD

**Issue by jrymer** [kekeh/mydatepicker#385]
None of the icons are displaying on the datepicker.

Angular cli 1.2.0

<img width="498" alt="screen shot 2017-07-24 at 10 46 17 am" src="https://user-images.githubusercontent.com/10549648/28529120-b670000e-705d-11e7-9232-f11d244ce10c.png">

**Comment by kekeh** [comment]
You can try to add the following to your css file:

```css
.mydp .mydpicon:before { 
    font-family: mydatepicker !important; 
}
```
