### ISSUE TITLE
How to use cutom class dynamically on date selection .

### ISSUE THREAD

**Issue by pratiksha-chandel** [kekeh/mydatepicker#433]

**Comment by kekeh** [comment]
You can try to override styles: https://github.com/kekeh/mydatepicker#change-styles-of-the-component

this is not reliable way and probably it is not working.

current styles of selected year, month and day. You try override these values.
```css
.mydp .selectedday .datevalue,
.mydp .selectedmonth .monthvalue,
.mydp .selectedyear .yearvalue {
    border: none;
    background-color: #8EBFFF;
    border-radius: 2px;
}
```
